services:
  db-starter:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
#      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=starterdb
      - MYSQL_USER=starterdb
      - MYSQL_PASSWORD=starterdb123
    ports:
      - 3306:3306
    volumes:
      - ./db-starter:/var/lib/mysql